[package]
name = "dotty"
description = "An insanely simple dotfiles management tool"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
dirs = "5.0.1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
